name: Build Oiygram APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK manually
      run: |
        echo "SDK_URL=https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" >> $GITHUB_ENV
        mkdir -p $HOME/android/sdk/cmdline-tools/latest
        wget -q $SDK_URL -O sdk.zip
        unzip -q sdk.zip -d $HOME/android/sdk/cmdline-tools/
        mv $HOME/android/sdk/cmdline-tools/cmdline-tools/* $HOME/android/sdk/cmdline-tools/latest/
        rm -rf $HOME/android/sdk/cmdline-tools/cmdline-tools/ sdk.zip
        
        export ANDROID_HOME=$HOME/android/sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        
        echo "ANDROID_HOME=$HOME/android/sdk" >> $GITHUB_ENV
        echo "$HOME/android/sdk/platform-tools" >> $GITHUB_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK (Release)
      run: ./gradlew assembleRelease

    - name: Upload generated APK
      uses: actions/upload-artifact@v4
      with:
        name: Oiygram-Release
        path: app/build/outputs/apk/release/*.apk
